 const actionTypes = {
    FETCHING_START:'FETCHING_START',
    FETCHING_SUCCESS:'FETCHING_SUCCESS',
    FETCHING_ERROR:'FETCHING_ERROR',
    // User action
    GETTING_USER_START:'GETTING_USER_START',
    GETTING_USER_SUCCESS:'GETTING_USER_SUCCESS',
    GETTING_USER_ERROR:'GETTING_USER_ERROR',
    //Cart
    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    DECREMENT_CART:'DECREMENT_CART'
}

export default actionTypes