 const actionTypes = {
    FETCHING_START:'FETCHING_START',
    FETCHING_SUCCESS:'FETCHING_SUCCESS',
    FETCHING_ERROR:'FETCHING_ERROR',
    // User action
    GETTING_USER_START:'GETTING_USER_START',
    GETTING_USER_SUCCESS:'GETTING_USER_SUCCESS',
    GETTING_USER_ERROR:'GETTING_USER_ERROR',
}

export default actionTypes